using UnityEngine;
using LLMUnity;
using UnityEngine.UI;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;

public class PCLLMFunctions : CloudControllerLLM
{
    // Lazy Loading + Singleton pattern to access and utalise the UI Controller methods withing the LLM Function Caller
    // Code generated by CHATGPT. Sources used:
    // https://learn.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization
    // https://gameprogrammingpatterns.com/singleton.html
    private static CloudControllerLLM _cloudControllerLLM;

    private static CloudControllerLLM cloudControllerLLM
    {
        get
        {
            // If already cached and still valid, return it
            if (_cloudControllerLLM != null)
                return _cloudControllerLLM;

            // Otherwise, find it in the scene and cache it
            _cloudControllerLLM = FindFirstObjectByType<CloudControllerLLM>();

            if (_cloudControllerLLM == null)
                Debug.LogWarning("PointCloudController not found in scene!");

            return _cloudControllerLLM;
        }
    }

    public static string functionPrompt = "";

    // Test Methods providing randomly generated results within string reply
    // static System.Random random = new System.Random();
    // public static string PointBudget()
    // {
    //     string[] pointBudget = new string[]{"200.000", "400.000", "750.000", "1.000.000"};
    //     return "The Point Budget of the Point Cloud is " + pointBudget[random.Next(pointBudget.Length)];
    // }
    // public static string PCClassCount()
    // {
    //     return "The Point Cloud contains: " + random.Next(5).ToString("D2") + " Classes, with: " + random.Next(10).ToString("D2") + " Total Instances";
    // }
    // public static string PCColorMode()
    // {
    //     string[] pCColorsMode = new string[] { "RGBA", "Classification", "Intensity" };
    //     return "Current color mode is set to: " + pCColorsMode[random.Next(pCColorsMode.Length)];
    // }

    // Methods with Access to the UI Controller

    // Methods to control the class toggles
    // Terrain
    public static bool HideTerrain()
    {
        cloudControllerLLM.classToggles[0].isOn = false;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Terrain Point Cloud Class (class 1) has been hidden";
        functionPrompt = "The function HideTerrain has been selected";
        return true;
    }
    public static bool ShowTerrain()
    {
        cloudControllerLLM.classToggles[0].isOn = true;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Terrain Point Cloud Class (class 1) is visible again";
        functionPrompt = "The function ShowTerrain has been selected";
        return true;
    }
    // Top
    public static bool HideTop()
    {
        cloudControllerLLM.classToggles[1].isOn = false;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Top Point Cloud Class (class 2) has been hidden";
        functionPrompt = "The function HideTop has been selected";
        return true;
    }
    public static bool ShowTop()
    {
        cloudControllerLLM.classToggles[1].isOn = true;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Top Point Cloud Class (class 2) is visible again";
        functionPrompt = "The function ShowTop has been selected";
        return true;
    }
    // Walls
    public static bool HideWalls()
    {
        cloudControllerLLM.classToggles[2].isOn = false;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Walls Point Cloud Class (class 3) has been hidden";
        functionPrompt = "The function HideWalls has been selected";
        return true;
    }
    public static bool ShowWalls()
    {
        cloudControllerLLM.classToggles[2].isOn = true;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Walls Point Cloud Class (class 3) is visible again";
        functionPrompt = "The function ShowWalls has been selected";
        return true;
    }
    // Tech
    public static bool HideTech()
    {
        cloudControllerLLM.classToggles[3].isOn = false;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Tech Point Cloud Class (class 4) has been hidden";
        functionPrompt = "The function HideTech has been selected";
        return true;
    }
    public static bool ShowTech()
    {
        cloudControllerLLM.classToggles[3].isOn = true;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Tech Point Cloud Class (class 4) is visible again";
        functionPrompt = "The function ShowTech has been selected";
        return true;
    }
    // Bottom
    public static bool HideBottom()
    {
        cloudControllerLLM.classToggles[4].isOn = false;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Bottom Point Cloud Class (class 5) has been hidden";
        functionPrompt = "The function HideBottom has been selected";
        return true;
    }
    public static bool ShowBottom()
    {
        cloudControllerLLM.classToggles[4].isOn = true;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "The Bottom Point Cloud Class (class 5) is visible again";
        functionPrompt = "The function ShowBottom has been selected";
        return true;
    }

    // Class Button Selection Methods. Prioritize a specific class and return the instance count for the selected class
    public static bool FocusOnTerrain()
    {
        cloudControllerLLM.ShowClassInstanceUI(1);
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(1);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "The function FocusOnTerrain has been selected";
        return true;
    }
    public static bool FocusOnTop()
    {
        cloudControllerLLM.ShowClassInstanceUI(2);
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(2);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "The function FocusOnTop has been selected";
        return true;
    }
    public static bool FocusOnWalls()
    {
        cloudControllerLLM.ShowClassInstanceUI(3);
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(3);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "The function FocusOnWalls has been selected";
        return true;
    }
    public static bool FocusOnTech()
    {
        cloudControllerLLM.ShowClassInstanceUI(4);
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(4);
        cloudControllerLLM.classToggles[2].isOn = !cloudControllerLLM.classToggles[2].isOn;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "The function FocusOnTech has been selected";
        return true;
    }
    public static bool FocusOnBottom()
    {
        cloudControllerLLM.ShowClassInstanceUI(5);
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(5);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "The function FocusOnBottom has been selected";
        return true;
    }
    
    // Method to reset the focus call, in case LLM won't call other focus functions
    public static bool UnFocusAll()
    {
        cloudControllerLLM.ResetSelection();
        cloudControllerLLM.ZoomToDefault();
        cloudControllerLLM.ResetClassToggles();
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        functionPrompt = "The function UnFocusAll has been selected";
        return true;
    }

    /* Function to help the user with controls, so that they can navigate the scene.
    //     public static string HelpNavigateScene()
    //     {
    //         return "To move around in the scene, always ensure that the right mouse button is down." +
    //         "You can then move the mouse to look around in the scene, and use the 'WASD', as well as the 'Q' and 'E' keys to move the camera position." +
    //         "While the AI Assist menu is hidden, you can use 'SPACE' to reset the camera position, " +
    //         "and press 'R' if you ever need to reload the Point Clouds." +
    //         " Hope this will help you navigate the scene." +
    //         "If there is anything you need help with, regarding manipulation of the Point Cloud, feel free to ask.";
    //     }*/

    // Methods to call when wanting to change the color mode of the point clouds 
    public static bool RGBAColorMode()
    {
        cloudControllerLLM.colorModeDropDown.value = 0;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "Displaying Point Clouds as colored by their RGBA values";
        functionPrompt = "The function RGBAColorMode has been selected";
        return true;
    }
    public static bool ClassificationColorMode()
    {
        cloudControllerLLM.colorModeDropDown.value = 1;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "Displaying Point Clouds as colored by their classification";
        functionPrompt = "The function ClassificationColorMode has been selected";
        return true;
    }
    public static bool IntensityColorMode()
    {
        cloudControllerLLM.colorModeDropDown.value = 2;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "Displaying Point Clouds as colored by their Intensity values";
        functionPrompt = "The function IntensityColorMode has been selected";
        return true;
    }

    // Methods for changing background 
    public static bool SetBackgroundSkybox()
    {
        cloudControllerLLM.SkyBoxButton();
        functionPrompt = "Background set to Skybox";
        return true;
    }
    public static bool SetBackgroundWhite()
    {
        cloudControllerLLM.WhiteButton();
        functionPrompt = "Background set to White";
        return true;
    }
    public static bool SetBackgroundBlack()
    {
        cloudControllerLLM.BlackButton();
        functionPrompt = "Background set to Black";
        return true;
    }
    
    // Method to reset function handler
    public static bool Conversation()
    {
        functionPrompt = "The function Conversation has been selected";
        return false;
    }
}


public class FunctionHandler : MonoBehaviour
{
    [SerializeField] LLMCharacter llmCharacter;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        llmCharacter.grammarString = MultipleChoiceGrammar();
    }

    // Update is called once per frame
    void Update()
    {

    }
    
    // Get the available functions within the Functions class
    string[] GetFunctionNames()
    {
        List<string> functionNames = new List<string>();
        foreach (var function in typeof(PCLLMFunctions).GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly)) functionNames.Add(function.Name);
        return functionNames.ToArray();
    }

    // Specfify grammar setup for the LLM (This one is set up for multiple choice responses)
    string MultipleChoiceGrammar()
    {
        return "root ::= (\"" + string.Join("\" | \"", GetFunctionNames()) + "\")";
    }

    // The prompt the LLM returns to the user
    string ConstructPrompt(string message)
    {
        string prompt = "You are an AI assistant that can select **ONE** function to execute\n\n";
        prompt += "if the input is just a question or normal chat, you **MUST** choose the function Conversation.\n\n";
        prompt += "if the input is a direct command that matches a function name, then execute **THAT** function.\n\n";
        prompt += "User Input:" + message + "\n\n";
        prompt += "Function Choices:\n";
        foreach (string functionName in GetFunctionNames()) prompt += $"- {functionName}\n";
        return prompt;
    }

    // Function within the function class which the LLM will try and call
    bool CallFunction(string functionName)
    {
        return (bool)typeof(PCLLMFunctions).GetMethod(functionName).Invoke(null, null);
    }

    // Method for when prompt has been submitted
    // async void onInputFieldSubmit(string message)
    // {
    //     playerText.interactable = false;
    //     string functionName = await llmCharacter.Chat(ConstructPrompt(message));
    //     string result = CallFunction(functionName);
    //     AIText.text = $"Calling {functionName}\n{result}";
    //     playerText.interactable = true;
    // }

    public async Task<(bool, string)> TryExecuteCommand(string message)
    {
        string functionName = await llmCharacter.Chat(ConstructPrompt(message));

        bool result = CallFunction(functionName);

        // if (result == true && message.Contains("background") && functionName.Contains("SetBackground"))
        // {
        //     if (message.Contains("black")) PCFunctions.SetBackground("Black");
        //     else if (message.Contains("white")) PCFunctions.SetBackground("White");
        //     else if (message.Contains("skybox")) PCFunctions.SetBackground("Skybox");
        //     return true;
        // }

        return (result, PCLLMFunctions.functionPrompt);
    }
}

