using UnityEngine;
using LLMUnity;
using UnityEngine.UI;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;

public class PCLLMFunctions : CloudControllerLLM
{
    // Lazy Loading + Singleton pattern to access and utalise the UI Controller methods withing the LLM Function Caller
    // Code generated by CHATGPT. Sources used:
    // https://learn.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization
    // https://gameprogrammingpatterns.com/singleton.html
    private static CloudControllerLLM _cloudControllerLLM;

    private static CloudControllerLLM cloudControllerLLM
    {
        get
        {
            // If already cached and still valid, return it
            if (_cloudControllerLLM != null)
                return _cloudControllerLLM;

            // Otherwise, find it in the scene and cache it
            _cloudControllerLLM = FindFirstObjectByType<CloudControllerLLM>();

            if (_cloudControllerLLM == null)
                Debug.LogWarning("PointCloudController not found in scene!");

            return _cloudControllerLLM;
        }
    }

    public static string functionPrompt = "";
    public static string contextPrompt = "";
    private static int currentFocus = 0; // 0 = no class focused
    private static bool activePBMenu = false;
    private static bool activeEDLMenu = false;
    private static bool activeExpViewMenu = false;
    private static bool EDLIsActive = true;

    // Method to show or hide the Point Budget Control Menu 
    /// <summary>
    /// This function opens up a menu for the user to control the point budget of all point clouds, using a slider from 0 to 1000000.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool PointBudgetControl()
    {
        cloudControllerLLM.PointBudgetMenu.SetActive(!activePBMenu);
        activePBMenu = !activePBMenu;
        functionPrompt = "The Point Budget Control Menu is now active";
        contextPrompt += functionPrompt;
        return true;
    }

    // Method to show or hide EDL Control Menu 
    /// <summary>
    /// This function opens up a menu for the user to control the EDL (eye-dome-lighting) effect applied to the point clouds. 
    /// Controls include an effect toggle (on/off); 
    /// EDL Radius slider (1-10); 
    /// EDL ExpScale slider (0.1-30); 
    /// EDL Scale slider (1-10).;
    /// </summary>
    /// <returns>bool true</returns>
    public static bool EDLControl()
    {
        cloudControllerLLM.EDLMenu.SetActive(!activeEDLMenu);
        activeEDLMenu = !activeEDLMenu;
        functionPrompt = "The EDL Control Menu is now active";
        contextPrompt += functionPrompt;
        return true;
    }

    // Method to turn EDL on or off directly 
    /// <summary>
    /// This function toggles the EDL on or off based on its current active state.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool EDLOnOff()
    {
        cloudControllerLLM.EDLToggle.isOn = !EDLIsActive;
        EDLIsActive = !EDLIsActive;
        functionPrompt = "The EDL Toggle has been set to " + EDLIsActive;
        contextPrompt += functionPrompt;
        return true;
    }

    // Method to hide the active menu
    /// <summary>
    /// This function hides any control menu that might be active, so that the user has less clutter on the screen.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool HideActiveControlMenu()
    {
        cloudControllerLLM.PointBudgetMenu.SetActive(false);
        activePBMenu = false;
        cloudControllerLLM.EDLMenu.SetActive(false);
        activeEDLMenu = false;
        cloudControllerLLM.ExplodedViewMenu.SetActive(false);
        activeExpViewMenu = false;
        functionPrompt = "The active control menu has been turned off.";
        contextPrompt += functionPrompt;
        return true;
    }

    /* // Methods to hide or show a specific class by name
    // // static System.Random random = new System.Random();
    // // public static string PointBudget()
    // // {
    // //     string[] pointBudget = new string[]{"200.000", "400.000", "750.000", "1.000.000"};
    // //     return "The Point Budget of the Point Cloud is " + pointBudget[random.Next(pointBudget.Length)];
    // // }
    // // public static string PCClassCount()
    // // {
    // //     return "The Point Cloud contains: " + random.Next(5).ToString("D2") + " Classes, with: " + random.Next(10).ToString("D2") + " Total Instances";
    // // }
    // // public static string PCColorMode()
    // // {
    // //     string[] pCColorsMode = new string[] { "RGBA", "Classification", "Intensity" };
    // //     return "Current color mode is set to: " + pCColorsMode[random.Next(pCColorsMode.Length)];
    // // }

    // // Methods with Access to the UI Controller

    // // Methods to control the class toggles
    // // Terrain
    // public static bool HideTerrain()
    // {
    //     cloudControllerLLM.classToggles[0].isOn = false;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Terrain Point Cloud Class (class 1) has been hidden";
    //     functionPrompt = "Class 1 (Terrain) is now hidden.";
    //     return true;
    // }
    // public static bool ShowTerrain()
    // {
    //     cloudControllerLLM.classToggles[0].isOn = true;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Terrain Point Cloud Class (class 1) is visible again";
    //     functionPrompt = "Class 1 (Terrain) is now visible.";
    //     return true;
    // }
    // // Top
    // public static bool HideTop()
    // {
    //     cloudControllerLLM.classToggles[1].isOn = false;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Top Point Cloud Class (class 2) has been hidden";
    //     functionPrompt = "Class 2 (Top) is now hidden.";
    //     return true;
    // }
    // public static bool ShowTop()
    // {
    //     cloudControllerLLM.classToggles[1].isOn = true;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Top Point Cloud Class (class 2) is visible again";
    //     functionPrompt = "Class 2 (Top) is now visible.";
    //     return true;
    // }
    // // Walls
    // public static bool HideWalls()
    // {
    //     cloudControllerLLM.classToggles[2].isOn = false;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Walls Point Cloud Class (class 3) has been hidden";
    //     functionPrompt = "Class 3 (Walls) is now hidden.";
    //     return true;
    // }
    // public static bool ShowWalls()
    // {
    //     cloudControllerLLM.classToggles[2].isOn = true;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Walls Point Cloud Class (class 3) is visible again";
    //     functionPrompt = "Class 3 (Walls) is now visible.";
    //     return true;
    // }
    // // Tech
    // public static bool HideTech()
    // {
    //     cloudControllerLLM.classToggles[3].isOn = false;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Tech Point Cloud Class (class 4) has been hidden";
    //     functionPrompt = "Class 4 (Tech) is now hidden.";
    //     return true;
    // }
    // public static bool ShowTech()
    // {
    //     cloudControllerLLM.classToggles[3].isOn = true;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Tech Point Cloud Class (class 4) is visible again";
    //     functionPrompt = "Class 4 (Tech) is now visible.";
    //     return true;
    // }
    // // Bottom
    // public static bool HideBottom()
    // {
    //     cloudControllerLLM.classToggles[4].isOn = false;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Bottom Point Cloud Class (class 5) has been hidden";
    //     functionPrompt = "Class 5 (Bottom) is now hidden.";
    //     return true;
    // }
    // public static bool ShowBottom()
    // {
    //     cloudControllerLLM.classToggles[4].isOn = true;
    //     cloudControllerLLM.keyboardShotcutsEnabled = true;
    //     cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
    //     //return "The Bottom Point Cloud Class (class 5) is visible again";
    //     functionPrompt = "Class 5 (Bottom) is now visible.";
    //     return true;
    // } */

    // Class Button Selection Methods. Prioritize a specific class and return the instance count for the selected class
    /// <summary>
    /// This function puts focus on the first class in the point cloud (the terrain). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass1Terrain()
    {
        if (currentFocus == 0)
        {
            currentFocus = 1;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
            cloudControllerLLM.ResetClassToggles();
            currentFocus = 1;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(1);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "Class 1 (Terrain) has been prioritiesed.";
        contextPrompt += functionPrompt;
        return true;
        
    }
    /// <summary>
    /// This function puts focus on the second class in the point cloud (the top of the wells). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass2Top()
    {
        cloudControllerLLM.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 2;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
            cloudControllerLLM.ResetClassToggles();
            currentFocus = 2;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(2);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "Class 2 (Top) has been prioritiesed.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the third class in the point cloud (the walls of the wells). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass3Walls()
    {
        cloudControllerLLM.classToggles[0].isOn = false;
        cloudControllerLLM.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 3;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
            cloudControllerLLM.ResetClassToggles();
            currentFocus = 3;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(3);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "Class 3 (Walls) has been prioritiesed.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the fourth class in the point cloud (the Tech of the well). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// The third class (walls) is hidden as to not block for this class. 
    /// Laslty a menu is spawned that shows all instances within the class");
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass4Tech()
    {
        cloudControllerLLM.classToggles[0].isOn = false;
        cloudControllerLLM.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 4;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
            cloudControllerLLM.ResetClassToggles();
            currentFocus = 4;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(4);
        cloudControllerLLM.classToggles[2].isOn = !cloudControllerLLM.classToggles[2].isOn;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "Class 4 (Tech) has been prioritiesed.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the fifth class in the point cloud (the pipes within the well). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass5Pipes()
    {
        cloudControllerLLM.classToggles[0].isOn = false;
        cloudControllerLLM.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 5;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
            cloudControllerLLM.ResetClassToggles();
            currentFocus = 5;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(5);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "Class 5 (Pipes) has been prioritiesed.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the sixth class in the point cloud (the bottom of the well). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass6Bottom()
    {
        cloudControllerLLM.classToggles[0].isOn = false;
        cloudControllerLLM.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 5;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
            cloudControllerLLM.ResetClassToggles();
            currentFocus = 5;
            cloudControllerLLM.ShowClassInstanceUI(currentFocus);
        }
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.ZoomToClass(5);
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        functionPrompt = "Class 6 (Bottom) has been prioritiesed.";
        contextPrompt += functionPrompt;
        return true;
    }
    
    // Method to reset the focus call, in case LLM won't call other focus functions
    /// <summary>
    /// This function resets focus to the default. 
    /// The camera is moved to an angle that gives the user the best overview of the whole point cloud. 
    /// All highlight colors are removed. 
    /// Laslty the menu showcasing all instances within the class is hidden.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ResetClassFocus()
    {
        currentFocus = 0;
        cloudControllerLLM.ResetSelection();
        cloudControllerLLM.ZoomToDefault();
        cloudControllerLLM.ResetClassToggles();
        cloudControllerLLM.ExplodedViewSlider.value = 0;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        functionPrompt = "Adjustments to the point cloud have been reset. Clearing context string.";
        contextPrompt += functionPrompt;
        return true;
    }

    /* Function to help the user with controls, so that they can navigate the scene.
    //     public static string HelpNavigateScene()
    //     {
    //         return "To move around in the scene, always ensure that the right mouse button is down." +
    //         "You can then move the mouse to look around in the scene, and use the 'WASD', as well as the 'Q' and 'E' keys to move the camera position." +
    //         "While the AI Assist menu is hidden, you can use 'SPACE' to reset the camera position, " +
    //         "and press 'R' if you ever need to reload the Point Clouds." +
    //         " Hope this will help you navigate the scene." +
    //         "If there is anything you need help with, regarding manipulation of the Point Cloud, feel free to ask.";
    //     }*/

    // Methods to call when wanting to change the color mode of the point clouds 
    /// <summary>
    /// This function converts the point cloud into an RGB colored version. 
    /// Each point in the cloud gets colored by its RGB values. 
    /// This is the default color mode.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool RGBAColorMode()
    {
        cloudControllerLLM.colorModeDropDown.value = 0;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "Displaying Point Clouds as colored by their RGBA values";
        functionPrompt = "Point cloud has been colored based on point RGB values.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function converts the point cloud into a Classification colored version. 
    /// Each point in the cloud gets colored by its classification.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ClassificationColorMode()
    {
        cloudControllerLLM.colorModeDropDown.value = 1;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "Displaying Point Clouds as colored by their classification";
        functionPrompt = "Point cloud has been colored based on point classification.";
        contextPrompt += functionPrompt;
        return true;
    }
    /*
    /// <summary>
    /// This function converts the point cloud into an Intensity colored version. 
    /// Each point in the cloud gets colored by its intensity.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool IntensityColorMode()
    {
        cloudControllerLLM.colorModeDropDown.value = 2;
        cloudControllerLLM.keyboardShotcutsEnabled = true;
        cloudControllerLLM.StartCoroutine(cloudControllerLLM.ReloadClouds());
        //return "Displaying Point Clouds as colored by their Intensity values";
        functionPrompt = "I have colored the point cloud based on point intensity.";
        contextPrompt += functionPrompt;
        return true;
    }*/

    // Methods for changing background 
    /// <summary>
    /// This function converts the background of the scene into the 'skybox' background.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool SetBackgroundSkybox()
    {
        cloudControllerLLM.SkyBoxButton();
        functionPrompt = "The Background has been set to 'Skybox'.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function converts the background of the scene into a 'white' background.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool SetBackgroundWhite()
    {
        cloudControllerLLM.WhiteButton();
        functionPrompt = "The Background has been set to 'White'.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function converts the background of the scene into a 'black' background.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool SetBackgroundBlack()
    {
        cloudControllerLLM.BlackButton();
        functionPrompt = "The Background has been set to 'Black'.";
        contextPrompt += functionPrompt;
        return true;
    }
    
    // Method to show or hide Exploded View Control Menu 
    /// <summary>
    /// This function opens up a menu for the user to control the seperation of classes along the y-axis to better visualise depth relations between classes. 
    /// A slider can be moved from 0 to 200, changing the level of separation between classes.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ExplodedViewController()
    {
        cloudControllerLLM.ExplodedViewMenu.SetActive(!activeExpViewMenu);
        activeExpViewMenu = !activeExpViewMenu;
        functionPrompt = "The menu for exploded view should now be active. \nadjust the slider to separate classes along the y-axis.";
        contextPrompt += functionPrompt;
        return true;
    }

    // Method to set Exploded View Slider value to specific value with a set camera position to quickly "explode" the point cloud
    /// <summary>
    /// This function sets a default value of 16 into the Exploded View Slider, and moves the camera to a set location, in order to quickly show the user the depth relations of each class.;
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ExplodePointCloud()
    {
        currentFocus = 7;
        cloudControllerLLM.ExplodedViewSlider.value = 25;
        cloudControllerLLM.ZoomToClass(currentFocus);
        functionPrompt = "I have 'exploded' the point cloud.";
        contextPrompt += functionPrompt;
        return true;
    }
    
    // Method to reset function handler and let LLM engage in Conversation
    /// <summary>
    /// This function changes the state of the LLM to engage in conversation with the user instead of executing a function. 
    /// If the user input does not match with any of the above mentioned functions, then use the user input for conversation instead.
    /// </summary>
    /// <returns>bool false</returns>
    public static bool Conversation()
    {
        functionPrompt = "The function Conversation has been selected";
        return false;
    }
}


public class FunctionHandler : MonoBehaviour
{
    [SerializeField] LLMCharacter llmCharacter;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        llmCharacter.grammarString = MultipleChoiceGrammar();
    }

    // Update is called once per frame
    void Update()
    {

    }
    
    // Get the available functions within the Functions class
    string[] GetFunctionNames()
    {
        List<string> functionNames = new List<string>();
        foreach (var function in typeof(PCLLMFunctions).GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly)) functionNames.Add(function.Name);
        return functionNames.ToArray();
    }
    // // Get the available functions within the Functions class
    // string[] GetFunctionDescriptions()
    // {
    //     List<string> functionDescription = new List<string>();
    //     foreach (var function in typeof(PCLLMFunctions).GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly)) functionDescription.Add(function.
    //     return functionDescription.ToArray();
    // }

    // Specfify grammar setup for the LLM (This one is set up for multiple choice responses)
    string MultipleChoiceGrammar()
    {
        return "root ::= (\"" + string.Join("\" | \"", GetFunctionNames()) + "\")";
    }

    // The prompt the LLM returns to the user
    string ConstructPrompt(string message)
    {
        string prompt = "You are an AI assistant that **MUST** select **ONE** function to execute\n\n";
        prompt += "if the input is just a question or normal chat, you **MUST** choose the function Conversation.\n\n";
        prompt += "if the input is a direct command that matches a function name, then execute **THAT** function.\n\n";
        prompt += "User Input:" + message + "\n";
        prompt += "Function Choices:\n";
        foreach (string functionName in GetFunctionNames()) prompt += $"- {functionName}\n";
        // prompt += "\nFunction Descriptions:\n";
        // foreach (string functionDescription in GetFunctionDescriptions()) prompt += $"- {functionDescription}\n";

        return prompt;
    }

    // Function within the function class which the LLM will try and call
    bool CallFunction(string functionName)
    {
        return (bool)typeof(PCLLMFunctions).GetMethod(functionName).Invoke(null, null);
    }

    // Method for when prompt has been submitted
    // async void onInputFieldSubmit(string message)
    // {
    //     playerText.interactable = false;
    //     string functionName = await llmCharacter.Chat(ConstructPrompt(message));
    //     string result = CallFunction(functionName);
    //     AIText.text = $"Calling {functionName}\n{result}";
    //     playerText.interactable = true;
    // }

    public async Task<(bool, string, string)> TryExecuteCommand(string message)
    {
        string functionName = await llmCharacter.Chat(ConstructPrompt(message));

        bool result = CallFunction(functionName);

        // if (result == true && message.Contains("background") && functionName.Contains("SetBackground"))
        // {
        //     if (message.Contains("black")) PCFunctions.SetBackground("Black");
        //     else if (message.Contains("white")) PCFunctions.SetBackground("White");
        //     else if (message.Contains("skybox")) PCFunctions.SetBackground("Skybox");
        //     return true;
        // }

        return (result, PCLLMFunctions.functionPrompt, PCLLMFunctions.contextPrompt);
    }
}

