using UnityEngine;
using LLMUnity;
using UnityEngine.UI;
using System.Collections.Generic;
using System.Reflection;
using Unity.VisualScripting;
public class PCFunctions : UIInstanceController
{
    // Lazy Loading + Singleton pattern to access and utalise the UI Controller methods withing the LLM Function Caller
    // Code generated by CHATGPT. Sources used:
    // https://learn.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization
    // https://gameprogrammingpatterns.com/singleton.html
    private static UIInstanceController _uIInstanceController;

    private static UIInstanceController uIInstanceController
    {
        get
        {
            // If already cached and still valid, return it
            if (_uIInstanceController != null)
                return _uIInstanceController;

            // Otherwise, find it in the scene and cache it
            _uIInstanceController = FindFirstObjectByType<UIInstanceController>();

            if (_uIInstanceController == null)
                Debug.LogWarning("PointCloudController not found in scene!");

            return _uIInstanceController;
        }
    }

    // Test Methods providing randomly generated results within string reply
    // static System.Random random = new System.Random();
    // public static string PointBudget()
    // {
    //     string[] pointBudget = new string[]{"200.000", "400.000", "750.000", "1.000.000"};
    //     return "The Point Budget of the Point Cloud is " + pointBudget[random.Next(pointBudget.Length)];
    // }
    // public static string PCClassCount()
    // {
    //     return "The Point Cloud contains: " + random.Next(5).ToString("D2") + " Classes, with: " + random.Next(10).ToString("D2") + " Total Instances";
    // }
    // public static string PCColorMode()
    // {
    //     string[] pCColorsMode = new string[] { "RGBA", "Classification", "Intensity" };
    //     return "Current color mode is set to: " + pCColorsMode[random.Next(pCColorsMode.Length)];
    // }

    // Methods with Access to the UI Controller

    // Methods to control the class toggles
    // Terrain
    public static string HideTerrain()
    {
        uIInstanceController.classToggles[0].isOn = false;
        return "The Terrain Point Cloud Class (class 1) has been hidden";
    }
    public static string ShowTerrain()
    {
        uIInstanceController.classToggles[0].isOn = true;
        return "The Terrain Point Cloud Class (class 1) is visible again";
    }
    // Top
    public static string HideTop()
    {
        uIInstanceController.classToggles[1].isOn = false;
        return "The Top Point Cloud Class (class 2) has been hidden";
    }
    public static string ShowTop()
    {
        uIInstanceController.classToggles[1].isOn = true;
        return "The Top Point Cloud Class (class 2) is visible again";
    }
    // Walls
    public static string HideWalls()
    {
        uIInstanceController.classToggles[2].isOn = false;
        return "The Walls Point Cloud Class (class 3) has been hidden";
    }
    public static string ShowWalls()
    {
        uIInstanceController.classToggles[2].isOn = true;
        return "The Walls Point Cloud Class (class 3) is visible again";
    }
    // Tech
    public static string HideTech()
    {
        uIInstanceController.classToggles[3].isOn = false;
        return "The Tech Point Cloud Class (class 4) has been hidden";
    }
    public static string ShowTech()
    {
        uIInstanceController.classToggles[3].isOn = true;
        return "The Tech Point Cloud Class (class 4) is visible again";
    }
    // Bottom
    public static string HideBottom()
    {
        uIInstanceController.classToggles[4].isOn = false;
        return "The Bottom Point Cloud Class (class 5) has been hidden";
    }
    public static string ShowBottom()
    {
        uIInstanceController.classToggles[4].isOn = true;
        return "The Bottom Point Cloud Class (class 5) is visible again";
    }

    // Class Button Selection Methods. Prioritize a specific class and return the instance count for the selected class
    public static string FocusOnTerrain()
    {
        uIInstanceController.ShowClassInstanceUI(1);
        if (uIInstanceController.classSelected[0] == true)
        {
            return "Prioritising the Terrain Clouds. Class contains: " + uIInstanceController.availableInstancesInClass + " instances";
        }
        else if (uIInstanceController.classSelected[0] == false)
        {
            return "Unprioritising the Terrain Clouds. Instance menu has been hidden, and cloud class point sizes have been reset";
        }
        return "";
    }
    public static string FocusOnTop()
    {
        uIInstanceController.ShowClassInstanceUI(2);
        if (uIInstanceController.classSelected[1] == true)
        {
            return "Prioritising the Top Clouds. Class contains: " + uIInstanceController.availableInstancesInClass + " instances";
        }
        else if (uIInstanceController.classSelected[1] == false)
        {
            return "Unprioritising the Top Clouds. Instance menu has been hidden, and cloud class point sizes have been reset";
        }
        return "";
    }
    public static string FocusOnWalls()
    {
        uIInstanceController.ShowClassInstanceUI(3);
        if (uIInstanceController.classSelected[2] == true)
        {
            return "Prioritising the Walls Clouds. Class contains: " + uIInstanceController.availableInstancesInClass + " instances";
        }
        else if (uIInstanceController.classSelected[2] == false)
        {
            return "Unprioritising the Walls Clouds. Instance menu has been hidden, and cloud class point sizes have been reset";
        }
        return "";
    }
    public static string FocusOnTech()
    {
        uIInstanceController.ShowClassInstanceUI(4);
        if (uIInstanceController.classSelected[3] == true)
        {
            return "Prioritising the Tech Clouds. Class contains: " + uIInstanceController.availableInstancesInClass + " instances";
        }
        else if (uIInstanceController.classSelected[3] == false)
        {
            return "Unprioritising the Tech Clouds. Instance menu has been hidden, and cloud class point sizes have been reset";
        }
        return "";
    }
    public static string FocusOnBottom()
    {
        uIInstanceController.ShowClassInstanceUI(5);
        if (uIInstanceController.classSelected[4] == true)
        {
            return "Prioritising the Bottom Clouds. Class contains: " + uIInstanceController.availableInstancesInClass + " instances";
        }
        else if (uIInstanceController.classSelected[4] == false)
        {
            return "Unprioritising the Bottom Clouds. Instance menu has been hidden, and cloud class point sizes have been reset";
        }
        return "";
    }

    // Function to help the user with controls, so that they can navigate the scene.
    public static string HelpNavigateScene()
    {
        return "To move around in the scene, always ensure that the right mouse button is down." +
        "You can then move the mouse to look around in the scene, and use the 'WASD', as well as the 'Q' and 'E' keys to move the camera position." +
        "While the AI Assist menu is hidden, you can use 'SPACE' to reset the camera position, " +
        "and press 'R' if you ever need to reload the Point Clouds." +
        " Hope this will help you navigate the scene." +
        "If there is anything you need help with, regarding manipulation of the Point Cloud, feel free to ask.";
    }

    // Methods to call when wanting to change the color mode of the point clouds 
    public static string RGBAColorMode()
    {
        uIInstanceController.colorModeDropDown.value = 0;
        return "Displaying Point Clouds as colored by their RGBA values";
    }
    public static string ClassificationColorMode()
    {
        uIInstanceController.colorModeDropDown.value = 1;
        return "Displaying Point Clouds as colored by their classification";
    }
    public static string IntensityColorMode()
    {
        uIInstanceController.colorModeDropDown.value = 2;
        return "Displaying Point Clouds as colored by their Intensity values";
    }
}

public class PointCloudAssistant : MonoBehaviour
{
    public LLMCharacter llmCharacter;
    public InputField playerText;
    public Text AIText;
    
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        playerText.onSubmit.AddListener(onInputFieldSubmit);
        playerText.Select();
        llmCharacter.grammarString = MultipleChoiceGrammar();
    }

    // Get the available functions within the Functions class
    string[] GetFunctionNames()
    {
        List<string> functionNames = new List<string>();
        foreach (var function in typeof(PCFunctions).GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly)) functionNames.Add(function.Name);
        return functionNames.ToArray();
    }

    // Specfify grammar setup for the LLM (This one is set up for multiple choice responses)
    string MultipleChoiceGrammar()
    {
        return "root ::= (\"" + string.Join("\" | \"", GetFunctionNames()) + "\")";
    }

    // The prompt the LLM returns to the user
    string ConstructPrompt(string message)
    {
        string prompt = "Which of the following choices matches best the input?\n\n";
        prompt += "Input:" + message + "\n\n";
        prompt += "Choices:\n";
        foreach (string functionName in GetFunctionNames()) prompt += $"- {functionName}\n";
        prompt += "\nAnswer directly with the choice";
        return prompt;
    }

    // Function within the function class which the LLM will try and call
    string CallFunction(string functionName)
    {
        return (string)typeof(PCFunctions).GetMethod(functionName).Invoke(null, null);
    }

    // Method for when prompt has been submitted
    async void onInputFieldSubmit(string message)
    {
        playerText.interactable = false;
        string functionName = await llmCharacter.Chat(ConstructPrompt(message));
        string result = CallFunction(functionName);
        AIText.text = $"Calling {functionName}\n{result}";
        playerText.interactable = true;
    }
    
    public void CancelRequests()
    {
        llmCharacter.CancelRequests();
    }

    public void ExitGame()
    {
        Debug.Log("Exit button clicked");
        Application.Quit();
    }

    // Ensure that an LLM Model is selected
    bool onValidateWarning = true;
    void OnValidate()
    {
        if (onValidateWarning && !llmCharacter.remote && llmCharacter.llm != null && llmCharacter.llm.model == "")
        {
            Debug.LogWarning($"Please select a model in the {llmCharacter.llm.gameObject.name} GameObject!");
            onValidateWarning = false;
        }
    }
}
