using UnityEngine;
using LLMUnity;
using UnityEngine.UI;
using System.Collections.Generic;
using System.Reflection;
using System.Threading.Tasks;

public class PCAIFunctions : PointCloudControls
{
    // Lazy Loading + Singleton pattern to access and utalise the UI Controller methods withing the LLM Function Caller
    // Code generated by CHATGPT. Sources used:
    // https://learn.microsoft.com/en-us/dotnet/framework/performance/lazy-initialization
    // https://gameprogrammingpatterns.com/singleton.html
    private static PointCloudControls _pointCloudControls;

    private static PointCloudControls pointCloudControls
    {
        get
        {
            // If already cached and still valid, return it
            if (_pointCloudControls != null)
                return _pointCloudControls;

            // Otherwise, find it in the scene and cache it
            _pointCloudControls = FindFirstObjectByType<PointCloudControls>();

            if (_pointCloudControls == null)
                Debug.LogWarning("PointCloudController not found in scene!");

            return _pointCloudControls;
        }
    }

    public static string functionPrompt = "";
    public static string contextPrompt = "";
    private static int currentFocus = 0; // 0 = no class focused
    private static bool EDLIsActive = true;

    // Method to turn EDL on or off directly 
    /// <summary>
    /// This function toggles the EDL on or off based on its current active state.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool EDLOnOff()
    {
        pointCloudControls.EDLToggle.isOn = !EDLIsActive;
        EDLIsActive = !EDLIsActive;
        functionPrompt = "You have set the EDL toggle to: " + EDLIsActive;
        contextPrompt += functionPrompt;
        return true;
    }

    // Class Button Selection Methods. Prioritize a specific class and return the instance count for the selected class
    /// <summary>
    /// This function puts focus on the first class in the point cloud (the terrain). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass1Terrain()
    {
        if (currentFocus == 0)
        {
            currentFocus = 1;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 1;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.ZoomToClassLLM(1);
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You have prioritiesed the Terrain (Class 1).";
        contextPrompt += functionPrompt;
        return true;
        
    }
    /// <summary>
    /// This function puts focus on the second class in the point cloud (the top of the wells). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass2Top()
    {
        pointCloudControls.classToggles[0].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 2;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 2;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.ZoomToClassLLM(2);
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You have prioritiesed the Top (Class 2).";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the third class in the point cloud (the walls of the wells). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass3Walls()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 3;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 3;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.ZoomToClassLLM(3);
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You have prioritiesed the Walls (Class 3).";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the fourth class in the point cloud (the Tech of the well). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible.
    /// Laslty a menu is spawned that shows all instances within the class");
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass4Tech()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 4;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 4;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.ZoomToClassLLM(4);
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You have prioritiesed the Internal Tech (Class 4).";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the fifth class in the point cloud (the pipes within the well). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass5Pipes()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 5;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 5;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.ZoomToClassLLM(3);
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You have prioritiesed the Connection Pipes (Class 5).";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function puts focus on the sixth class in the point cloud (the bottom of the well). 
    /// The camera is moved to an angle that gives the user the best overview of this cloud class. 
    /// A red highlight color is added to make the current priority more visible. 
    /// Laslty a menu is spawned that shows all instances within the class.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ShowClass6Bottom()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 6;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 6;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.ZoomToClassLLM(4);
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You have prioritiesed the Bottom (Class 6).";
        contextPrompt += functionPrompt;
        return true;
    }
    
    /// <summary>
    /// This function puts focus on the instance 'debris_screen' in the point cloud for class 4 (the internal tech class). 
    /// The camera is moved to an angle that gives the user the best overview of this instance. 
    /// A blue highlight color is added to make the current instance more visible. 
    /// Other instances are marked red (if not also selected).
    /// Laslty the menu for instances in class is spawned.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool FindDebrisScreen()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 4;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 4;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.SelectCloudClassInstance(currentFocus, 1);
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You are showcasing the Debris Screen (instance 1) within Class 4.";
        contextPrompt += functionPrompt;
        return true;
    }

    /// <summary>
    /// This function puts focus on the instance 'flow_control_gate' in the point cloud for class 4 (the internal tech class). 
    /// The camera is moved to an angle that gives the user the best overview of this instance. 
    /// A blue highlight color is added to make the current instance more visible. 
    /// Other instances are marked red (if not also selected).
    /// Laslty the menu for instances in class is spawned.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool FindFlowControlGate()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 4;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 4;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.SelectCloudClassInstance(currentFocus, 2);
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You are showcasing the Flow Control Gate (instance 2) within Class 4.";
        contextPrompt += functionPrompt;
        return true;
    }

    /// <summary>
    /// This function puts focus on the instance 'inlet_outlet' in the point cloud for class 5 (the Pipes class). 
    /// The camera is moved to an angle that gives the user the best overview of this instance. 
    /// A blue highlight color is added to make the current instance more visible. 
    /// Other instances are marked red (if not also selected).
    /// Laslty the menu for instances in class is spawned.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool FindInletOutlet()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 5;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 5;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.SelectCloudClassInstance(currentFocus, 1);
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You are showcasing the Inlet and Outlet Pipes (instance 1) within Class 5.";
        contextPrompt += functionPrompt;
        return true;
    }

    /// <summary>
    /// This function puts focus on the instance 'conduit' in the point cloud for class 5 (the Pipes class). 
    /// The camera is moved to an angle that gives the user the best overview of this instance. 
    /// A blue highlight color is added to make the current instance more visible. 
    /// Other instances are marked red (if not also selected).
    /// Laslty the menu for instances in class is spawned.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool FindConduit()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 5;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 5;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.SelectCloudClassInstance(currentFocus, 2);
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You are showcasing the Conduit (instance 2) within Class 5.";
        contextPrompt += functionPrompt;
        return true;
    }

    /// <summary>
    /// This function puts focus on the instance 'retention_bassin' in the point cloud for class 6 (the Bottom class). 
    /// The camera is moved to an angle that gives the user the best overview of this instance. 
    /// A blue highlight color is added to make the current instance more visible. 
    /// Other instances are marked red (if not also selected).
    /// Laslty the menu for instances in class is spawned.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool FindRetentionBassin()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 6;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 6;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.SelectCloudClassInstance(currentFocus, 1);
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You are showcasing the Retention Bassin (instance 1) within Class 6.";
        contextPrompt += functionPrompt;
        return true;
    }

    /// <summary>
    /// This function puts focus on the instance 'spillway' in the point cloud for class 6 (the Bottom class). 
    /// The camera is moved to an angle that gives the user the best overview of this instance. 
    /// A blue highlight color is added to make the current instance more visible. 
    /// Other instances are marked red (if not also selected).
    /// Laslty the menu for instances in class is spawned.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool FindSpillway()
    {
        pointCloudControls.classToggles[0].isOn = false;
        pointCloudControls.classToggles[1].isOn = false;
        if (currentFocus == 0)
        {
            currentFocus = 6;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        else
        {
            pointCloudControls.ShowClassInstanceUI(currentFocus);
            pointCloudControls.ResetClassToggles();
            currentFocus = 6;
            pointCloudControls.ShowClassInstanceUI(currentFocus);
        }
        pointCloudControls.SelectCloudClassInstance(currentFocus, 2);
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        functionPrompt = "You are showcasing the Spillway (instance 2) within Class 6.";
        contextPrompt += functionPrompt;
        return true;
    }
    
    // Method to reset the focus call, in case LLM won't call other focus functions
    /// <summary>
    /// This function resets focus to the default. 
    /// The camera is moved to an angle that gives the user the best overview of the whole point cloud. 
    /// All highlight colors are removed. 
    /// Laslty the menu showcasing all instances within the class is hidden.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ResetPointCloud()
    {
        currentFocus = 0;
        pointCloudControls.ResetSelection();
        pointCloudControls.ZoomToDefault();
        pointCloudControls.ResetClassToggles();
        pointCloudControls.ExplodedViewSlider.value = 0;
        pointCloudControls.keyboardShotcutsEnabled = true;
        functionPrompt = "You have reset the point cloud to default setup.";
        contextPrompt += functionPrompt;
        return true;
    }

    // Methods to call when wanting to change the color mode of the point clouds 
    /// <summary>
    /// This function converts the point cloud into an RGB colored version. 
    /// Each point in the cloud gets colored by its RGB values. 
    /// This is the default color mode.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool RGBColorMode()
    {
        pointCloudControls.colorModeDropDown.value = 0;
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        //return "Displaying Point Clouds as colored by their RGBA values";
        functionPrompt = "You have colored points in the point clouds, based RGB values.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function converts the point cloud into a Classification colored version. 
    /// Each point in the cloud gets colored by its classification.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ClassificationColorMode()
    {
        pointCloudControls.colorModeDropDown.value = 1;
        pointCloudControls.keyboardShotcutsEnabled = true;
        pointCloudControls.StartCoroutine(pointCloudControls.ReloadClouds());
        //return "Displaying Point Clouds as colored by their classification";
        functionPrompt = "You have colored points in the point clouds, based on classification.";
        contextPrompt += functionPrompt;
        return true;
    }

    // Methods for changing background 
    /// <summary>
    /// This function converts the background of the scene into the 'skybox' background.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool SetBackgroundSkybox()
    {
        pointCloudControls.SkyBoxButton();
        functionPrompt = "The Background has been set to 'Skybox'.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function converts the background of the scene into a 'white' background.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool SetBackgroundWhite()
    {
        pointCloudControls.WhiteButton();
        functionPrompt = "The Background has been set to 'White'.";
        contextPrompt += functionPrompt;
        return true;
    }
    /// <summary>
    /// This function converts the background of the scene into a 'black' background.
    /// </summary>
    /// <returns>bool true</returns>
    public static bool SetBackgroundBlack()
    {
        pointCloudControls.BlackButton();
        functionPrompt = "The Background has been set to 'Black'.";
        contextPrompt += functionPrompt;
        return true;
    }

    // Method to set Exploded View Slider value to specific value with a set camera position to quickly "explode" the point cloud
    /// <summary>
    /// This function sets a default value of 16 into the Exploded View Slider, and moves the camera to a set location, in order to quickly show the user the depth relations of each class.;
    /// </summary>
    /// <returns>bool true</returns>
    public static bool ExplodePointCloud()
    {
        currentFocus = 7;
        pointCloudControls.ExplodedViewSlider.value = 25;
        pointCloudControls.ZoomToClassLLM(currentFocus);
        currentFocus = 0;
        functionPrompt = "You have 'exploded' the point cloud. \n Classes are separated based on the slider value of 25 for the exploded view. \n Camera has been moved for all clouds to be visible.";
        contextPrompt += functionPrompt;
        return true;
    }
    
    // Method to reset function handler and let LLM engage in Conversation
    /// <summary>
    /// This function changes the state of the LLM to engage in conversation with the user instead of executing a function. 
    /// If the user input does not match with any of the above mentioned functions, then use the user input for conversation instead.
    /// </summary>
    /// <returns>bool false</returns>
    public static bool Conversation()
    {
        functionPrompt = "You are engaging in conversation.";
        return false;
    }
}


public class LLMFunctionHandler : MonoBehaviour
{
    [SerializeField] LLMCharacter llmCharacter;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        llmCharacter.grammarString = MultipleChoiceGrammar();
    }

    // Update is called once per frame
    void Update()
    {

    }
    
    // Get the available functions within the Functions class
    string[] GetFunctionNames()
    {
        List<string> functionNames = new List<string>();
        foreach (var function in typeof(PCAIFunctions).GetMethods(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly)) functionNames.Add(function.Name);
        return functionNames.ToArray();
    }

    // Specfify grammar setup for the LLM (This one is set up for multiple choice responses)
    string MultipleChoiceGrammar()
    {
        return "root ::= (\"" + string.Join("\" | \"", GetFunctionNames()) + "\")";
    }

    // The prompt the LLM returns to the user
    string ConstructPrompt(string message)
    {
        string prompt = "You are an AI assistant that **MUST** select **ONE** function to execute\n\n";
        prompt += "if the input is just a question or normal chat, you **MUST** choose the function Conversation.\n\n";
        prompt += "if the input is a direct command that matches a function name, then execute **THAT** function.\n\n";
        prompt += "User Input:" + message + "\n";
        prompt += "Function Choices:\n";
        foreach (string functionName in GetFunctionNames()) prompt += $"- {functionName}\n";

        return prompt;
    }

    // Function within the function class which the LLM will try and call
    bool CallFunction(string functionName)
    {
        return (bool)typeof(PCAIFunctions).GetMethod(functionName).Invoke(null, null);
    }

    public async Task<(bool, string, string)> TryExecuteCommand(string message)
    {
        string functionName = await llmCharacter.Chat(ConstructPrompt(message));

        bool result = CallFunction(functionName);

        return (result, PCAIFunctions.functionPrompt, PCAIFunctions.contextPrompt);
    }
}

